### ISSUE TITLE
namespaced tag and attribute names?

### ISSUE THREAD

**Issue by cambiata** [benmerckx/ithril#10]
When dealing with svgs, you occasionally need to use namespaced attributes. (Maybe tags too.)
Example: defining symbols and referring to those with the `<use` tag, including `xlink:href="id"`
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/symbol

Of course, this has to be synced with how mithril handles this (if it does?).

**Comment by benmerckx** [comment]
I found this: https://github.com/lhorie/mithril.js/issues/620
But I'm currently not able to test, and unsure what this would render server side. But we should be able to support this once I have time to check out if there's any changed needed.

**Comment by benmerckx** [comment]
Supporting namespaced tags will be harder, could you give me an example of one? Haxe parsing wouldn't allow (namespace:tag) so I'd have to build in support for something like ('namespace:tag') or find a better way.

**Comment by cambiata** [comment]
Namespaced tags are definitely not high priority - the idea comes up because of ithril's cross-platform rendering possibilities, wich makes it a candidate for a more general xml building tool...

**Comment by benmerckx** [comment]
I've now mimicked the behaviour of mithril for the server side rendering (in ithril 1.0.8). What this means is the namespace declaration on svg is no longer required or needed (xmlns="http://www.w3.org/2000/svg"), it will be set automatically and the namespaced xlink:href must be set as simply `href`. Something like this should now correctly render on server and client:

``` haxe
(svg)
  (a (href="http://example.com/link/"))
    (text (x="10", y="25") > 'Link')
```

**Comment by cambiata** [comment]
Wow, that's great! Thx!
