### ISSUE TITLE
Server rendering: Value rendered to input, but not to texarea

### ISSUE THREAD

**Issue by cambiata** [benmerckx/ithril#6]
Hi Ben!

While playing with serverside (neko) ithril, I find that in the following example, the `testInt` value is rendered correctly into the input element, while the textarea element is blank.
(When rendered clientside, both elements are rendered with the `testInt` value - as expected.)

Bug or feature?

```
class Index extends Component {
    public function view() [
        (title > 'Index')
        (meta[charset="utf-8"])
        (meta[name="viewport"][content="width=device-width, initial-scale=1.0"])
        (link[href="style.css"][rel="stylesheet"])
        (body)
            [body()]
    ];  

    public static var testInt = 123;

    @:access(ithril.component.ComponentCache)
    public function body() {[
        (div)
            (textarea (value  = '$testInt'))
            (input (value = '$testInt'))
    ]; }
}

```

**Comment by benmerckx** [comment]
This happens because a textarea's innerHTML can be set directly through `value` in javascript, but this will not work when set as attribute (eg `<textarea value="test"></textarea>` will render blank).
The correct way to approach this is rewriting it like this for example: `(textarea > testInt)`

**Comment by cambiata** [comment]
Ah, as simple as that! Thanks!
