### ISSUE TITLE
Server rendering of non-string values causes Exception

### ISSUE THREAD

**Issue by cambiata** [benmerckx/ithril#7]
Noticed the following minors:

```
    (textarea > 123) // works client- and serverside
    (input(value = 123)) // causes exception serverside
```

and the somewhat related:

```
    public static var anonObj = {a:1};
    ...
    (div > '$anonObj') // works both client- and serverside
    (div > anonObj) // doesn't render anytning clientside (reasonable!) but causes exception serverside
```

**Comment by benmerckx** [comment]
Thanks, I'll get that fixed!

**Comment by benmerckx** [comment]
I've fixed the first problem in https://github.com/benmerckx/ithril/commit/6b1a3d23dceefb7b4e414e1884b697030d4a1ff9 (1.0.8 on haxelib). 
I don't think the second case needs fixing - an exception is probably more reasonable than suppressing it.

**Comment by cambiata** [comment]
Thx!
