### ISSUE TITLE
Building ithril views programmatically? 

### ISSUE THREAD

**Issue by cambiata** [benmerckx/ithril#8]
Is it  possible to somehow sidestep the templating part of ithril and instead build the view data dom tree programmatically?

To give a background: In my work with music notation, I build complex svg files (or openfl or cairo...) using an interface with the graphical components that I need. Something like:

```
class TargetSvg implements ITargetGraphics {
    public function new() { // instantiate an svg dom xml... }
    public function drawLine(x1, y1 ... ) { // add an svg line element to the xml... }
    public function drawCircle(x, y, r) { // add an svg circle element to the xml...}
}

class TargetOpenfl implements ITargetGraphics {
    public function new() { // instantiate a flash api sprite container }
    public function drawLine(x1, y1 ...) { // draw a line on the container sprite using flash api }
    public function drawCircle(x, y, r) { // draw a circle on the container sprite using flash api }
}
```

As it seems that mithril js handles svgs pretty well: 
Would it be possible to - in the same manner - instantiate a ithril view root object (in my case an svg) and then programmatically add elements (svg lines, circles or whatever) to that, preferrably using the same interface?

**Comment by cambiata** [comment]
Or - using another (maybe simpler) approach:
Could I just programmatically build the string representation of an ithril view (fairly easy!) and feed ithril with that? Something like

```
var viewStr = '
(svg (width="100px", height="50px"))
    (g)
        (circle(cx="10", cy="10", r="5"))
';
```

**Comment by benmerckx** [comment]
Hi Jonas, I'm not entirely sure what goal is here. Would it be like adding a TargetMithril that has the same interface, which would then render client side?

**Comment by cambiata** [comment]
Yes, a TargetMithril that could be used both server- and clientside.

Another example for the programmatical approach would be to implement a IthrilRenderer for the markdown library. https://github.com/dpeek/haxe-markdown/blob/master/src/markdown. There is a HtmlRenderer that just gives plain html output, and I've myself created a HaxeDomRenderer that builds the html via HaxeDom classes (this gives me finetuned control - I can use my own custom markdown tags and make them render interactive elements for example.) I'm using this HaxeDomRenderer when live-editing markdown data clientside, but HaxeDom's isomorphism lets me start by rendering the pages serverside.

If the same approach  done building ithril views (usable server- and clientside) instead of HaxeDom, I would get the dom-diff feature as a bonuns on top.

**Comment by cambiata** [comment]
Delved a bit deeper into this, and it seems that I can be monitoring state changes in the `setState` method, and programmatically build the customized child structure from there by using the `setChildren` method. 

Works with initial server rendering, and clientside dom-diffing - just as I wanted. :+1:  Hopefully I will be able to contribute some example on this - maybe a live markdown editor or something.

**Comment by benmerckx** [comment]
Alright, I was going to write up an example today but it seems you've found a way :)

**Comment by cambiata** [comment]
Thanx for doing great stuff :+1:
