### ISSUE TITLE
Avoiding extra wrapping of child elements?

### ISSUE THREAD

**Issue by cambiata** [benmerckx/ithril#9]
Is there a way to avoid wrapping the component children?

If not, there is obviously introduced an extra node level that might be 1) unwanted but not causing any notable problem, or 2) breaking the structure of for example svg elements.

This is how I understand that it works right now:
Let's say that I want to create a parent div component and add paragraph children to it. 
In the example below every child paragraph is wrapped in an unwanted span:

```
class Parent extends Component {
    public function view() [
        (div)
            (child in children)
                (span > child)  // all child items are wrapped in a unnecessary span
    ];
}

class Child extends Component<String> {
    public function view() [ (p > state) ];
]
```

I can fully understand that the view parser syntactically "need" a parent element definition.

One (a bit hackish) way of getting around this could be to introduce a reserved view tag (like "raw" or something) for outputting a child element directly without wrapping it. Somewhat like this:

```
class Parent extends Component {
    public function view() [
        (div)
            (child in children)
                (raw > child)  // "raw" renders the child item as it is without wrapping it 
    ];
}
```

?

**Comment by benmerckx** [comment]
That's what brackets are for :) They allow any expression to be passed into your template:

``` haxe
(child in children)
  [child]
```

It can be used for anything: `[functionCall()]`, `['string']`, `[if(true) 'this' else 'that']`, ...

**Comment by cambiata** [comment]
Ah, thought that had tried that..!
Thanks!
